config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'welcome/index'
  resources :articles, only: [:index, :show]
  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :update, :destroy, :edit]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
   @post = Post.new post_params
    if @post.save
      redirect_to @post, notice: "文章创建成功!"
    else
      render 'new', notice: "文章创建失败!"
    end
  end
  
  def edit
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, notice: "文章删除成功!"
    end
  end

  def update
     if @post.update post_params
        redirect_to @post, notice: "文章更改成功!" 
     else
        render 'edit', notice: "文章修改失败!"
     end
  end


  private
    def post_params
      params.require(:post).permit(:title, :content)
    end

    def find_post
      @post = Post.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @posts = Post.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1 id="page_title">Stuff I've Written</h1>

<div id="posts_wrapper" class="skinny_wrapper">
  
  <% @posts.each do |post| %>
    <div class="post">
      <p class="date"><%= post.created_at.strftime("%Y-%m-%d") %></p>
      <h2><%= link_to post.title, article_path(post) %></h2>
      <hr>
    </div>
  <% end %>


</div>

<div class="pagination">
  <sapn class="previous_page disabled">Previous</sapn>
  <em class="current">1</em>
  <a href="" rel="next">2</a>
  <a href="" class="next_page">Next</a>
</div>

app/views/articles/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">

  <header>
    <p class="date"><%= @post.created_at.strftime("%Y-%m-%d") %></p>
    <h2><%= @post.title %></h2>
    <hr>
  </header>

  <div id="content">
    <%= markdown(@post.content) %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mackenzie Child - Part Designer, Part Developer</title>
  <lipnk href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header id="main_navigation" class="clearfix">
  <%= link_to 'Hikaru', root_path, class: "name" %>
  <nav>
    <%= link_to 'Articles', articles_path %>
    <a href="#">Projects</a>
    <a href="#">Contact</a>
  </nav>
</header> 

<%= yield %>

<footer id="main_footer">
  <p class="copyright">&copy2015 Hikaru</p>
  <nav>
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-qq"></i></a>
    <a href="#"><i class="fa fa-weixin"></i></a>
  </nav>
</footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <% if @post.errors.any? %>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

  <%= f.label :title %> 
   <br />
  <%= f.text_field :title %>

  <br />
  <br />

  <%= f.label :content %>
  <br />
  <%= f.text_area :content %>

  <br />
  <br />

  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div class="center">
  <h1>修改文章</h1>
  <%= render 'form' %>
</div>

app/views/posts/new.html.erb
<div class="center">
  <h1>Article New</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="center">
  <h1>Articles Show</h1>
    <%= @post.title %>
    <br />
    <%= markdown(@post.content) %>
    <br />
    <br >
  <%= link_to 'edit', edit_post_path(@post), class: "btn btn-info" %>
  <%= link_to 'destroy', post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"  %>
</div>

app/views/welcome/index.html.erb
  <h1 id="page_title">Stuff I've Written</h1>

  <div id="posts_wrapper" class="skinny_wrapper">
    
    <% @posts.each do |post| %>
      <div class="post">
        <p class="date"><%= post.created_at.strftime('%Y-%m-%d') %></p>
        <h2><a href="#"><%= link_to post.title, post %></a></h2>
        <hr>
      </div>
    <% end %>

  <div class="post">
    <p class="date">Friday April 10th</p>
    <h2><a href="#">The Do List</a></h2>
    <hr>
  </div>

  <div class="post">
    <p class="date">Friday April 10th</p>
    <h2><a href="#">The Do List</a></h2>
    <hr>
  </div>

  </div>

  <div class="pagination">
    <sapn class="previous_page disabled">Previous</sapn>
    <em class="current">1</em>
    <a href="" rel="next">2</a>
    <a href="" class="next_page">Next</a>
  </div>